name: "Using Secrets"

on:
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "${{ secrets.TOP_SECRET }}"
          echo "${{ secrets.NOT_THERE }}"
          echo $ENV_SECRET
        env:
          ENV_SECRET: ${{ secrets.TOP_SECRET }}
