name: "Using Secrets"

on:
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "Top secret: ${{ secrets.TOP_SECRET }}"
          echo "Not there: ${{ secrets.NOT_THERE }}"
          echo "From the environment: $ENV_SECRET"
        env:
          ENV_SECRET: ${{ secrets.TOP_SECRET }}
